### ISSUE TITLE
Justification for elevation

### ISSUE THREAD

**Issue by Astorias96** [pseymour/MakeMeAdmin#101]
Hello Pseymour,

I am wondering if you could add the possibility to enforce (or not) to ask a justification when a user is elevating its account ?

Thank you in advance for your help.
Astorias96

**Comment by pseymour** [comment]
This is already in the master branch. It was issue 3. This version is unreleased, but I am working on wrapping it up. It will be version 2.4.

**Comment by Astorias96** [comment]
Hello Patrick,

Many thanks for your feedback, happy to read that this is something you are looking forward to integrate in version 2.4.

By any chance, do you know when you will release it ? I have worked on an in-house solution in the meantime, using Powershell (for the dialog and other stuff) and a scheduled task (to enforce the use of the dialog).

Looking forward for your proposal on this.

Have a nice day,
Astorias96

**Comment by pseymour** [comment]
I don't have a timeline. I have to work with external translators, update the changelog, and add the new stuff to the documentation. 

The version number in the master branch has been changed (currently 2.3.81), so when it is finally 2.4, you'll be able to upgrade to the final release easily.

**Comment by Astorias96** [comment]
Thanks a lot for your feedback ! Looking forward for this update.
Regards,
Astorias96
