### ISSUE TITLE
How to uninstall leaving current user in Administrator group?

### ISSUE THREAD

**Issue by Shadimar** [pseymour/MakeMeAdmin#103]
Is this possible?  I'm trying to figure out a way to have our MDM be able to 'remove' MakeMeAdmin and leave the user as a local administrator.  It seems when I uninstall the application it removes the current user from the Administrator group automatically.

**Comment by pseymour** [comment]
Make Me Admin does not work like that. Sounds like a PowerShell script would work, provided your MDM can do that.

**Comment by Shadimar** [comment]
Not sure how I’d be able to use powershell to help?  I’m not a powershell pro but our MDM can definitely push powershell scripts.
________________________________
