### ISSUE TITLE
admin privileges required to run setup

### ISSUE THREAD

**Issue by JustaC0mmonNoob** [pseymour/MakeMeAdmin#107]
its sad that i cant make myself an admin

**Comment by JustaC0mmonNoob** [comment]
can you guys help out please ?

**Comment by pseymour** [comment]
Admin rights are required, because the software installs a service. 

Even if this was not a requirement, if I made an app to allow standard users to elevate themselves without an admin first installing it, the IT community would have me drawn and quartered.

**Comment by JustaC0mmonNoob** [comment]
oh
