### ISSUE TITLE
Account not being removed from local Administrators group after 24 hours

### ISSUE THREAD

**Issue by amullan01** [pseymour/MakeMeAdmin#108]
We are installing Make Me Admin via SCCM and Software Center.
Our package creates the following registry value during installation:
    HKEY_LOCAL_MACHINE\SOFTWARE\Sinclair Community College\Make Me Admin
    Value name: Admin Rights Timeout
    Value Data: 1440 (Decimal)

Logged in as local user, run Make Me Admin.
Click Grant Me Administrator Rights button.
Confirmed user account is added to the local Administrators group.

Expected behavior:
    User account is removed from the local administrators group after 24 hours

Observed behavior:
    User account is still in the local administrator account even after 27 hours.

Strangely, we confirmed that the user account is removed from local administrators group after 28 hours with the following value:
    Value name: Admin Rights Timeout
    Value Data:  680 (Hexadecimal)
    
Environment details:
    Windows 10 Version 22H2
    Domain joined PC
    Using local (non-domain) account for testing
    Make Me Admin version 2.3.0

**Comment by rayzilt** [comment]
Are you sure that you enter the values as decimal? 680 Hexadecimal is around 1664 minutes (27 hour and a bit).
1440 Hexadecimal is 86 hours.

**Comment by amullan01** [comment]
My apologies, indeed it was not correct, I was relying on the word of someone else, when I asked them to redo and confirm again that the value is in decimal and 1440, it works perfectly and the account was removed after exactly 24 hours.
This issue can be closed. Thanks.
