### ISSUE TITLE
EncryptedSettings Error

### ISSUE THREAD

**Issue by batesm** [pseymour/MakeMeAdmin#11]
Hi. I am getting a CryptographicException thrown when it loads the EncryptedSettings from file. This throws a fault exception from the WCF service.

What do I need to do to recover from this? Clearly for whatever reason it won't decrypt the settings on my machine anymore

Thanks!

**Comment by pseymour** [comment]
Try deleting the users.xml file from `%ProgramData%\Make Me Admin`.

**Comment by pseymour** [comment]
I haven't heard back, so I'm closing this issue.
