### ISSUE TITLE
Service start error at MakeMeAdmin MSI installation (v2.3)

### ISSUE THREAD

**Issue by Astorias96** [pseymour/MakeMeAdmin#110]
Hello Pseymour,

I try to install Make Me Admin v2.3 on a Windows 10 computer (version 1809) using the packaged MSI that was downloaded on Github/Releases. the installer copies all the files and fails to start the service. A dialog appears telling that the service could not be started, then, when hitting retry, it fails again. Cancelling the installation removes the binaries. The UI could start during installation, but gets removed after cancellation.

I activated MSI installer logging, this is the associated logfile:

MSI (s) (5C:3C) [10:43:32:556]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI89F0.tmp, Entrypoint: ExecServiceConfig
MSI (s) (5C:C4) [10:43:32:557]: Generating random cookie.
MSI (s) (5C:C4) [10:43:32:560]: Created Custom Action Server with PID 12756 (0x31D4).
MSI (s) (5C:F0) [10:43:32:590]: Running as a service.
MSI (s) (5C:F0) [10:43:32:592]: Hello, I'm your 32bit Elevated Non-remapped custom action server.
MSI (s) (5C:54) [10:43:32:599]: Executing op: ActionStart(Name=StartServices,Description=Starting services,Template=Service: [1])
MSI (s) (5C:54) [10:43:32:599]: Executing op: ProgressTotal(Total=1,Type=1,ByteEquivalent=1300000)
MSI (s) (5C:54) [10:43:32:599]: Executing op: ServiceControl(,Name=MakeMeAdmin,Action=1,Wait=1,)
MSI (s) (5C:54) [10:47:36:573]: Note: 1: 2205 2: 3: Error
MSI (s) (5C:54) [10:47:36:573]: Note: 1: 2228 2: 3: Error 4: SELECT Message FROM Error WHERE Error = 1920
MSI (c) (B0:00) [10:47:36:578]: Font created. Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

Error 1920. Service 'Make Me Admin' (MakeMeAdmin) failed to start. Verify that you have sufficient privileges to start system services.
MSI (s) (5C:54) [10:49:04:468]: Note: 1: 2205 2: 3: Error
MSI (s) (5C:54) [10:49:04:468]: Note: 1: 2228 2: 3: Error 4: SELECT Message FROM Error WHERE Error = 1709
MSI (s) (5C:54) [10:49:04:468]: Product: Make Me Admin -- Error 1920. Service 'Make Me Admin' (MakeMeAdmin) failed to start. Verify that you have sufficient privileges to start system services.

MSI (s) (5C:54) [10:53:08:453]: Note: 1: 2205 2: 3: Error
MSI (s) (5C:54) [10:53:08:453]: Note: 1: 2228 2: 3: Error 4: SELECT Message FROM Error WHERE Error = 1920
MSI (s) (5C:0C) [10:53:08:476]: I/O on thread 4896 could not be cancelled. Error: 1168
MSI (s) (5C:0C) [10:53:08:476]: I/O on thread 17436 could not be cancelled. Error: 1168
MSI (s) (5C:0C) [10:53:08:476]: I/O on thread 13652 could not be cancelled. Error: 1168
MSI (s) (5C:0C) [10:53:08:476]: I/O on thread 5572 could not be cancelled. Error: 1168
MSI (s) (5C:54) [10:53:08:477]: Note: 1: 2205 2: 3: Error
MSI (s) (5C:54) [10:53:08:477]: Note: 1: 2228 2: 3: Error 4: SELECT Message FROM Error WHERE Error = 1709
MSI (s) (5C:54) [10:53:08:477]: Product: Make Me Admin -- Error 1920. Service 'Make Me Admin' (MakeMeAdmin) failed to start. Verify that you have sufficient privileges to start system services.

I also tried to start it manually, it fails. The MSI was started with administrator rights, even though I understood from some issues here that it might not be required. Can you please help ? If required, I can DM you the full logfile.

PS: While looking up the error code 1902, I found this thread:
https://stackoverflow.com/questions/20061057/error-1920-service-failed-to-start-verify-that-you-have-sufficient-privileges-t

I will try some suggestions in the meantime.
Thank you in advance for your help.

Kind regards,
Astorias96

**Comment by Astorias96** [comment]
Hello scottcopus,
Thank you for your message. Yes, the log I provided (MSI installation) comes from an elevated command prompt installation with administrative rights.

**Comment by scottcopus** [comment]
@Astorias96 My only other suggestions at the moment are to "unblock" the installer, try a different MakeMeAdmin version/installer, or try a different computer or VM (vanilla Windows w/ no 3rd party antivirus, etc).

**Comment by pseymour** [comment]
1809?!

**Comment by Astorias96** [comment]
@scottcopus , the file was not blocked by any AV. I installed it on many other devices (that use the same GPO/AV configuration) without any issues, only these 3 have issues.

I will try to figure out what software is causing interferences, for now I am looking if .NET framework reinstallation and software clean-up (the 3 affected devices are developer endpoints) can help. 

@pseymour : I know the version is old. I would love to move to a newer version, but this is out of my reach. The other devices in 1809 have MakeMeAdmin installed and this is working fine. I will update this thread with the solution when I figured it out.

**Comment by Astorias96** [comment]
Just adding another note (so if someone has the same issue this might help): Using the version 2.3.81 in 64-bit mode worked like a charm. It seems the mentioned issue was then corrected in this version, as the service started without an issue on the affected devices (with a regular installation on 64-bit, no extra steps).

@pseymour : Even tough these devices use Windows 10 Enterprise LTSC and this version has been released on 02/10/2018, it is still under long term service channel and I am not seeing why this should have been an issue with the MMA version 2.3. As the issue seems solved on MMA version 2.3.81, I am unsure how relevant the versioning was at this stage. LTSC editions receive security updates and are still in the list of supported editions on many constructors until their end of life date (1809 - 09/2029).

Using a newer version allowed MMA to work as intended on the affected devices.
