### ISSUE TITLE
Make me admin unable to grant adminstrator rights

### ISSUE THREAD

**Issue by kayjay707** [pseymour/MakeMeAdmin#112]
![Pasted image](https://github.com/pseymour/MakeMeAdmin/assets/160749687/cfa4678c-8b40-477c-9487-fa416b131572)

Hello,

There was a power outage and after the PC was restarted, MMA has been unable to grant this user the admin access. Upon checking the past issues, I tried following steps from this reply: https://github.com/pseymour/MakeMeAdmin/issues/28#issuecomment-765240744

But the "Make Me Admin" folder does not exist under roaming. Is there any other way I can fix this?

Thanks

**Comment by Jimmy-Painter** [comment]
Seeing the same issue on my devices. #28 also did not work for me. Has anyone found a solution to this yet?

**Comment by kayjay707** [comment]
Hey @pseymour,

Could you please help here?

Thanks

**Comment by pseymour** [comment]
Did you check for a users.xml in both locations? See my comment right before the #28 you linked.

**Comment by kayjay707** [comment]
@pseymour,

Hello, yes I checked for the users.xml file in both locations. I could not find the folder names Make Me Admin anywhere.. Please advice.

Thanks

**Comment by kayjay707** [comment]
@pseymour

Could you please help here?

Thanks

**Comment by pseymour** [comment]
I don't have much to go on, just a screenshot that says it didn't work, and you saying the users.xml file does not exist. I don't know which version you're using, anything else you've done to try to resolve this, etc.  I'm a one-person operation here, and we're doing this over the Internet. You have to provide information, or I can't be of much assistance.

For example, if you're using the released version (2.3), the users.xml file, and therefore the Make Me Admin folder that contains it, are created right after the service launches, which is right after installation. In the version that's in the master branch now, the file is created the first time you add a user to the Administrators group.  Either way, I find it odd that you do not have this folder at all.
