### ISSUE TITLE
Regedit

### ISSUE THREAD

**Issue by MagnusBroman** [pseymour/MakeMeAdmin#20]
I installed verion MakeMeAdmin 2.3.0 x64 of Make me admin on a Swedish Windows 10 1909 but I do not get it not to work with the attribute "Allowed Entities" when I start the application so I never get up the choice "Grant me admin..." but the "Automatic Add Allowed" attribute works fine. I have tried to enter only userid, userid@domain.se, sid but nothing helps do you have any tips that can help me?

**Comment by pseymour** [comment]
The "Allowed Entities" value should contain either SIDs or names in the format of "DOMAIN\user-name-here" or "DOMAIN\group-name-here."  Using user principal names (UPNs) won't work. Here's an example of the two formats:

![image](https://user-images.githubusercontent.com/39745121/99301974-bcffad00-281c-11eb-8d8b-376d6d3b66dc.png)

**Comment by pseymour** [comment]
I saw the thumbs up. Did you get it working?

**Comment by MagnusBroman** [comment]
Its works great, thanks for fast response

**Comment by pseymour** [comment]
Updated the wiki to show how names must be specified.
