### ISSUE TITLE
Administrator rights kept after reboot

### ISSUE THREAD

**Issue by Niekvdm** [pseymour/MakeMeAdmin#21]
**Issue**
After granting rights using MakeMeAdmin and rebooting the machine the administrator rights will be kept indefinitely until MakeMeAdmin is launched again.

**Possible solution**
Since the service does not retain its state after rebooting I suggest completely removing the administrator rights when the MakeMeAdmin service is first launched upon boot.

**Comment by pseymour** [comment]
The service does retain state between reboots, and users are removed after their timeout elapses.  What you are describing is the default behavior. It can be disabled with the `Remove Admin Rights On Logout` [setting](https://github.com/pseymour/MakeMeAdmin/wiki/Registry-Settings).

As a side note, I have considered turning this setting on by default, as that is the more secure way to operate.

**Comment by Niekvdm** [comment]
I see thanks for the the clarification. Will try to use the Remove Admin Rights On Logout setting
