### ISSUE TITLE
Losing Administrator Rights after uninstalling "Make Me Admin"

### ISSUE THREAD

**Issue by FabianOSMOND** [pseymour/MakeMeAdmin#22]
Hello,
We are testing your application, and everything sounds good until we tested uninstall process.
So, we cannot recover the admin rights after uninstall.
User respected the uninstall process on Windows 10 by "add/remove application" from Windows 10 control panel.

Some precisions :
- We Use an Active-Directory
- User has admin rights by default on the computer
- Computer is Windows 10 Professional x64

I thank you for your help,

Best regards and Happy New Year !

**Comment by pseymour** [comment]
I'm not sure I understand the issue. You uninstalled Make Me Admin, and now you can't get administrator rights?

**Comment by FabianOSMOND** [comment]
Hello Patrick,
Yes that's it.

**Comment by pseymour** [comment]
Was there a reason for uninstalling it?  The rights granted by Make Me Admin are temporary, so in the ordinary course of things, you would not uninstall it. It just runs in the background, waiting for another request for admin rights to come from the user.
