### ISSUE TITLE
Error Message: reject client credentials

### ISSUE THREAD

**Issue by kristymadimike** [pseymour/MakeMeAdmin#24]
We're getting the follow error message when attempting to elevate:

Error Message: The server has rejected the client credentials

We've been using MakeMeAdmin in the environment for a bit now without any issues so I suspect that modifications in the laptop image we're using have caused the problems because we're only seeing it with recent laptops.

Any ideas where to look or have you seen this problem before?

**Comment by pseymour** [comment]
I've seen it in two situations: the user's password has expired, or the user's account is locked out.
