### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by johnnystenberg** [pseymour/MakeMeAdmin#26]
I wish you could clear the admin group from users not added by MakeMeAdmin. Potentially, a user could create a new local user and add that user to the admin group. It would be nice to have thoose cleared out.

**Comment by pseymour** [comment]
Probably could add that, but we just use Group Policy to force a certain membership list. Either Group Policy Preferences or the old-school Restricted Groups will work. Make Me Admin works just fine with a policy in place.

**Comment by johnnystenberg** [comment]
If it works well with Restricted groups. That will work just fine. Thank you

**Comment by pseymour** [comment]
Yep, that's what we used for a while, and then we moved to GP Preferences. Either way, what happens is that Make Me Admin watches to see if the user has been removed by an outside process before their rights have expired, and it puts them back in the admins group.
