### ISSUE TITLE
Make Me admin report or log

### ISSUE THREAD

**Issue by oxy6en** [pseymour/MakeMeAdmin#27]
Just wondering if there's a way to get the log file of the users that granted admin right which consists of:
Username, duration time between time admin granted and time when admin revoked.

**Comment by pseymour** [comment]
Those events are recorded in the Application event log, with a source of "Make Me Admin."

**Comment by oxy6en** [comment]
Hi Pseymour,

Thank you for your reply, my plan is to deploy "Make Me Admin" via ConfigMgr to all machines, so the end-users will be able to install and use it. However, we need something to monitor them. Just wondering if there's a way in "Make Me Admin" application to grab selected event (Make Me Admin) log files after time out /revoked and write on the server (sharefolder) which will have get date, get timestamp, get hostname, get username.

Cheers

**Comment by pseymour** [comment]
We use ConfigMgr also. I just extended the inventory in ConfigMgr to grab the Make Me Admin events from the event log as part of the normal inventory process. Now they're in the ConfigMgr inventory for safe keeping.

**Comment by paulbishton** [comment]
Hi @pseymour, we're also looking to same sort of logs/reports that @oxy6en was after.

Do you have any suggestions on how to pull this information in an Intune environment?

**Comment by pseymour** [comment]
No, I don't. We barely use Intune right now.

**Comment by pseymour** [comment]
Maybe this? I haven't tried it.

https://deviceadvice.io/2021/02/01/collect-windows-event-logs-using-log-analytics-and-intune/
