### ISSUE TITLE
Request: Option to require user to authenticate

### ISSUE THREAD

**Issue by PeetMcK** [pseymour/MakeMeAdmin#31]
Great project. Thank you for your work. 

I’m looking to implement this as the Windows equivalent to[Privileges.app](https://github.com/SAP/macOS-enterprise-privileges).  On of the features of Privileges.app is the ability to require the user to authenticate before they are granted admin rights. This hopefully keeps a third party from elevating rights without proving identity. 

Would it be possible to add this functionality?

**Comment by pseymour** [comment]
I suppose it's possible to add that, but I'm curious why one would do that. Right now, after you obtain admin rights, when you perform an action that requires those rights, you have to authenticate with UAC in order to proceed. If an attacker knows the credentials to satisfy UAC, they would know the credentials to satisfy a prompt from Make Me Admin itself.

**Comment by PeetMcK** [comment]
I was under the impression that the Administrators group membership was updated for a windows session without having to log in and out. I'm poking around to see if there's anyway force the currently running session to update without a log out. If there happens to be a way to do so, then that would be the answer.
But the secondary reason I'd like to auth is to have the experience of requesting privileges as close to the same on Windows as it is on MacOS using Privileges.app. On the Mac side users are required to auth their account and provide a reason for the privilege elevation. It may end up just being an unnecessary auth, but it is nice when processes like this are as close to the same on Windows as they are on macOS.
Nonetheless, I'm going to keep poking to see if there's anything restricted that a user may have access to immediately upon elevating their privileges.

**Comment by pseymour** [comment]
Nope, the list of groups is normally only refreshed when the user logs on.  You can do a `klist purge`, but Make Me Admin doesn't do that on the user's behalf. 

On Windows, there shouldn't be anything that requires admin privileges that a user can access once they're in the admins group, without authenticating.   That is, if I log into a Windows machine as a standard user, and then some process puts me into the Administrators group (remote help desk person, Make Me Admin, etc.), to do anything that requires admin privileges, I would have to authenticate.

**Comment by pseymour** [comment]
@PeetMcK can you try this version?

[branch for this](https://github.com/pseymour/MakeMeAdmin/tree/issue-31)

**Comment by PeetMcK** [comment]
The issue-31 branch is working with problems:

Enabling the "Require Authentication to Obtain Privileges" via GPO does cause a Windows Security authentication window to pop:
![Screen Shot 2021-03-11 at 12 53 20 PM](https://user-images.githubusercontent.com/68706879/110846225-c51aa700-8268-11eb-9cee-a80204e7de83.png)
If I enter a failed auth I get an auth error:
![Screen Shot 2021-03-11 at 1 03 57 PM](https://user-images.githubusercontent.com/68706879/110847526-40c92380-826a-11eb-947c-4cc26a9e6ad6.png)
If I enter correct authentication for the currently logged in and Make Me Admin Enabled user, it accepts it, but does not make the user an admin.
If I enter the correct authentication for a User with admin rights, the logged in user is added to the administrators group.
If I enter the correct authentication for another user that is a  Make Me Admin Enabled usert, the logged in user is added to the administrators group.

**Comment by pseymour** [comment]
Yes, the authentication box does need to be locked to the current user. Actually the user who is running MMA, which may not be the current Windows user.

I can't get it to fail to add the current user with correct credentials provided however.

**Comment by PeetMcK** [comment]
It seems to be related to password length. Set your password for your Make Me Admin Enabled user to 24+ characters and see if you can get it to fail?

**Comment by PeetMcK** [comment]
Now I was going to say that if there truly is nothing that a user can mangle or a malicious user can touch without hitting a UAC prompt, enabling "Remove Admin Rights On Logout" should fill any loopholes that may have popped up because of this. That does leave my desire that the experience is much the same on Windows with Make Me Admin as it is on macOS with Privileges.app, so for me personally I'm both excited and grateful that you're giving this a go. So big props and an even bigger thank you.

When a user is Make Me Admin Enabled (MMAE), locking the authentication prompt to the user running MMA is great. But  this current behavior could be a useful 'hidden feature' (I also could be overthinking it). Since the prompt allows for another MMAE user to raise the privileges of a currently logged in user, there could be a place for this workflow:

- User without Make Me Admin is logged in. 
- This user does not to be permanently Make Me Admin Enabled
- Helpdesk employee with Global Make Me Admin Enabled for all machines under their care is helping User via screen sharing.
- Helpdesk employee opens Make Me Admin and Alt + Clicks the "You are not authorized to use this application" button. 
- This pops the unlocked authentication prompt prompt and the helpdesk employee can allow the end user to perform the administrative task with the User's username/password.

So yeah, I'm probably overthinking it, but this would allow for an end user that might not yet be prepared to be MMAE to be provided window into what's required when they do have those rights. I'm imaging having this when I was running a helpdesk in Higher Ed. We had some faculty that could have been MMAE enabled with no questions. Some that would never be MMAE. But there were a lot of in-between folks that after a bit of learning would have gone from a not-quite-yet to MMAE. So having a workflow that they'd see step by step during a support session or two and that gave them the participation buy-in of using their own credentials could be helpful.

All that said, the same scenario could play out minus the use of the User's credentials if the helpdesk employee simply does a Shift + Right Click "Run as different user".

**Comment by pseymour** [comment]
24 characters?! You animal. :)

**Comment by PeetMcK** [comment]
I'll take a minimum 24 character password over a password expiration policy **any day of the week**! But yeah it takes some convincing to get clients on board. 🤣

**Comment by pseymour** [comment]
@PeetMcK I posted a new build last night. Did you see it?

**Comment by PeetMcK** [comment]
Just tried it. Authentication works as expected. Here are some thoughts:

- Like you've mentioned tying the authentication window to the user running MMA.
- If I type any user besides the user running MMA and a bogus password, the password prompt screen disappears for a moment and then reopens. 
If I type the MMAE user with the wrong password, I get this message, have to click okay:
![Screen Shot 2021-03-12 at 10 49 40 AM](https://user-images.githubusercontent.com/68706879/110978470-aaa40480-8320-11eb-98a2-40ba3a5cc1fb.png)



As an aside is it possible to keep the product ID the same for the installers in single branch? It's not that big of a deal, but I was about to report that it wasn't working when I realized that each build has it's own product ID and there were two instances of `Make Me Admin - Require Authentication for Rights` installed. If it creates any other hassles, please don't worry about it.

**Comment by PeetMcK** [comment]
In limited testing, it looks like the commit "Trying to satiate Peet. :)". 

I've done my best to break it or trip it up. 

- Dialog text looks good
- Auth window prompts for current user password
- Wrong password - Returns standard user or password is incorrect
- Authenticating as a different user returns to prompt for logged in user credentials.

Without trying anything actively evil, I can't seem to hit an error or confusing UI.

Bravo.

**Comment by pseymour** [comment]
Much appreciated, Peet. I've made notes to set a fixed Product ID for test branches. They'll need to go back to dynamically-generated for production builds, so hopefully I don't jack that up. :)

**Comment by Robobc** [comment]
How can I downaload MakeMeAdmin with this feature?

**Comment by Robobc** [comment]
Hi @pseymour, ty. How can I enable this feature? I cannot find the procedure within the wiki.
