### ISSUE TITLE
.\Name not working for Local Users and Groups 

### ISSUE THREAD

**Issue by PeetMcK** [pseymour/MakeMeAdmin#33]
I'm not top notch when it comes to programing, but it looks as though both %COMPUTERNAME%\Name and .\Name should work for local Groups and Users. The comments in [LocalAdministratorGroup.cs](https://github.com/pseymour/MakeMeAdmin/blob/5dd426ac80f662c295e4718b69124149e1f81f20/ProcessCommunication/LocalAdministratorGroup.cs) states:
```
Environment Variables will be expanded out. The following formats are accepted:
...
* .\\xxxx or %COMPUTERNAME%\\xxxx (local user or group - also accepts explicitly using the computer name)
...
```

However in my 2.3 install with`.\GroupName` in `Allowed Entities` ends with "You are not authorized to use this application". `%COMPUTERNAME%\GroupName` in Allowed Entities` works as expected. 

Thanks.Peet

**Comment by pseymour** [comment]
I tried using dot on a domain-joined and workgroup PC, and it works. Did you download the released version of 2.3, or the one from the current master branch?  If the former, please try the [installer](https://github.com/pseymour/MakeMeAdmin/tree/master/Installers/en-us) from the master branch.

**Comment by PeetMcK** [comment]
I'm deploying the Chocolaty installed x64 version, so the released version. I'll give the master branch a try. If that's the case I'll have to retool my deployment, but so it goes. Is there a new release on the horizon?

**Comment by PeetMcK** [comment]
Closing this up since .\Name works correctly in the Main branch.
