### ISSUE TITLE
Tracking how many end-user using Make Me Admin

### ISSUE THREAD

**Issue by oxy6en** [pseymour/MakeMeAdmin#46]
Hi,

Just wondering there any way to monitor end-user who use make me admin for temporary admin rights, such as computer name, username, time and duration. The reason I'm asking is looking a way to provide a report for auditing to track how many end-user using temporary admin rights.

Many thanks

**Comment by pseymour** [comment]
There is nothing built-in to the software to do this. Most people end up sending Make Me Admin events to a syslog server or capturing the Event Log events with whatever inventory tool they use (MS Configuration Manager, etc.).
