### ISSUE TITLE
question: Microsoft Multilingual App Toolkit and VS 2022

### ISSUE THREAD

**Issue by saadanerdetbare** [pseymour/MakeMeAdmin#51]
Is there a workaround for using Microsoft Multilingual App Toolkit? It is not as of now compatible with Visual Studio 2022. If not, maybe people could go upvote this issue on developer portal
https://developercommunity.visualstudio.com/t/multilingual-app-toolkit-not-available-on-vs2022/1590902

**Comment by pseymour** [comment]
This is now solved with MAT 4.1.

https://marketplace.visualstudio.com/items?itemName=dts-publisher.mat2022
