### ISSUE TITLE
option not to create shortcuts

### ISSUE THREAD

**Issue by KONIKPK** [pseymour/MakeMeAdmin#63]
It's possible to install option add install like a service?
We want use this tool in environment for managing computers but don't want user know this is installed on his computers.

**Comment by pseymour** [comment]
There is already a service running; it's how Make Me Admin is able to do its thing.

What are you trying to accomplish?

**Comment by KONIKPK** [comment]
i know its just a service.
We want there was no start menu item, desktop icon or so, in users computer, so they don't try running it atc..

**Comment by pseymour** [comment]
You could just delete the shortcuts with Group Policy Preferences, or with whatever your desktop management system is.

**Comment by KONIKPK** [comment]
Yes i know we do it like this but it wil be fine if there was switch in installer.
