### ISSUE TITLE
Don't see settings in regedit

### ISSUE THREAD

**Issue by NeverForget1410** [pseymour/MakeMeAdmin#73]
Hello, 

I'm writing with question, why i can not see settings in regedit. I can go to
`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\ ` 
but don't see **Sinclair Community College\Make Me Admin**

I want to say i work in company and use domain user and i want to change time from 10 min to for examle 30min.
Any sugestion chow to change it ? :D

**Comment by pseymour** [comment]
If any registry key doesn't exist, you have to create it. Make Me Admin is no different.

**Comment by NeverForget1410** [comment]
> 

Is it possible that Make Me Admin dont make any registy key and work normaly?

So i shoud create in Policies key `Sinclair Community College` and in tkis key another key named : `Make Me Admin`
Then in key Make Me Admin create REG_DWORD (32bit) with name **Admin Rights Timeout**  and value  30  and thats it?

**Comment by pseymour** [comment]
Yes to both of your questions. If you didn't have admin rights, then you  couldn't have installed Make Me Admin.
