### ISSUE TITLE
Registry Keys Not Appearing (Win10)

### ISSUE THREAD

**Issue by i-am-naut** [pseymour/MakeMeAdmin#77]
After installing via the MSI, I am unable to find the registry keys in order to configure settings. The ones listed in the wiki 

`HKEY_LOCAL_MACHINE\SOFTWARE\Sinclair Community College\Make Me Admin`

`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Sinclair Community College\Make Me Admin`

Do not exist anywhere in the registry. Any suggestions?

**Comment by pseymour** [comment]
They don't exist unless you make them. Of course, using the Group Policy templates would create the keys under Policies for you.

**Comment by i-am-naut** [comment]
![image](https://user-images.githubusercontent.com/86634398/191825885-90fe82e4-6dfb-49fe-815a-4b12691e8295.png)

It all makes sense now...

**Comment by vatu4016** [comment]
I feel so dumb, was struggling with writing a PS script that would automatically install the msi and change the key value from 10 to 60 the last 4 days assuming they path and key would exist after installation, damn.
