### ISSUE TITLE
Admin persistence on reboot 

### ISSUE THREAD

**Issue by Zeppperoni** [pseymour/MakeMeAdmin#80]
Hello, 

I noticed an issue with MakeMeAdmin where when a user escalated privileges if they reboot the machines they will have admin permissions on login. When the application is opened up again then the permissions are removed.

is this expect behaviour?

This can be fixed with a startup script that removes admins from any domain users.

Thanks in advance!

**Comment by pseymour** [comment]
The default setting for removing admin rights when the user logs off is false, meaning rights will not be removed. Admittedly this is the less secure option, but that is the default for now.

You can change the "Remove Admin Rights On Logout" setting to true (1), and that behavior will stop.
