### ISSUE TITLE
where are the GPO settings

### ISSUE THREAD

**Issue by mmenzie** [pseymour/MakeMeAdmin#82]
Where are the GPO settings? i downloaded the app and installed it and i do not see any GPO settings, i am not finding the "installation folder" either

**Comment by pseymour** [comment]
The installation folder is the folder to which you installed Make Me Admin.

**Comment by mmenzie** [comment]
> The installation folder is the folder to which you installed Make Me Admin.

but there are no GPO settings or files there. just the program itself

**Comment by pseymour** [comment]
![image](https://user-images.githubusercontent.com/39745121/200414302-1a4a4d1f-a962-440f-8aac-a4a34971b0a5.png)

This is what I see when I install the current MSI in the master branch.
