### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by LorenzISR** [pseymour/MakeMeAdmin#86]
I am trying to build this using `dotnet build`, but I am getting this error:
```
C:\Users\<removed>\dev\makemeadmin\WiXCustomAction\WiXCustomAction.csproj(85,5): error : The WiX Toolset v3.11 (o
r newer) build tools must be installed to build this project. To download the WiX Toolset, see http://wixtoolset.org/re
leases/
```

I installed the wix toolset, but I am still getting the same error as before. Do you know how to fix this?

Thanks in advance ;-)

**Comment by pseymour** [comment]
https://github.com/wixtoolset/issues/issues/5627

**Comment by LorenzISR** [comment]
What I mant to ask is, how are you building MakeMeAdmin?

**Comment by pseymour** [comment]
I just use Visual Studio.

**Comment by LorenzISR** [comment]
Ok. :+1:
