### ISSUE TITLE
make-me-admin and Windows 10 LTSC 2019 aka 1809 

### ISSUE THREAD

**Issue by impala-sc** [pseymour/MakeMeAdmin#90]
Posting here not expecting a fix, but to help anyone else trying the same thing.  I've tried to install make-me-admin 2.3 on two Windows 10 LTSC 2019 PCs and it fails when trying to start the make-me-admin service.  A compatibility wizard says it needs .NET 4.8.  When I try to install .NET 4.8 it says it is not supported on this OS.  
LTSC is a special version of Windows intended for long-term support and it is missing support for modern apps.  I suppose this is why .NET 4.8 does not work.  LTSC will never receive a feature update, but the advantage is it will be supported for security updates until December 2028 unlike mainstream Windows 10.  Also, feature updates sometimes break legacy software so they are unwanted in special cases.
I'm a github newbie and am fumbling around.  I found the make-me-admin 2.2.1 installer and got it working.  I could not find the documentation for 2.2.1 and it seems much has changed in 2.3.  I was able to add the allowed user SID to the normal Allowed Entities regkey, but using the .\userid format didn't work.

**Comment by pseymour** [comment]
Aside from the oddity of using an LTSC edition on end-user devices, a couple of notes:

1. .NET Framework 4.8 installed just fine on an LTSC 2019 VM I setup.
2. Make Me Admin 2.3, the [released version](https://github.com/pseymour/MakeMeAdmin/releases), runs on .NET Framework 4.5.2, which is built-in to LTSC 2019. The code was not moved to Framework 4.8 until [August, 2020](https://github.com/pseymour/MakeMeAdmin/commit/3855520e233f2249853f85e37546f66491112256).
