### ISSUE TITLE
Port 808 ist not listening

### ISSUE THREAD

**Issue by abdus1818** [pseymour/MakeMeAdmin#92]
With the latest Version of Make Me Admin Port 808 is not listening. 
netstat -an do not show Port 808 with latest Version, when I install the Version before Port 808 is visible there with stat Listening.
Therefore we cannot use the Remote Version

**Comment by abdus1818** [comment]
I get this error in application Log:
The Net.Tcp Port Sharing Service is disabled. Remote access will not be available.

**Comment by pseymour** [comment]
That message is displayed when the service's start mode is set to disabled. Is the service disabled?

**Comment by pseymour** [comment]
That code was added in August, 2020. Feel free to roll back to the [`version before that code existed`](https://github.com/pseymour/MakeMeAdmin/tree/cfa85caee5bff426324c7a00ea995cc0af9f166c).
