### ISSUE TITLE
User has not been granted the requested logon type - Status 0xc000015b (Windows 11)

### ISSUE THREAD

**Issue by frost-cqre** [pseymour/MakeMeAdmin#96]
When I try to grant myself admin rights on Windows 11 with the setting that I need to authenticate on granting rights, I get this error on initial authentication. Event Viewer reveals that I have not the permissions to perform logon type 3, which is network logon. If I grant myself the right "Access this computer from the network" it starts working.

Is this expected behaviour? If so, I might have to do some changes to our hardening policy.

**Comment by pseymour** [comment]
I haven't tested this, but the MSFT docs suggest lots of issues could occur if you remove this right.

https://support.microsoft.com/en-us/topic/client-service-and-program-issues-can-occur-if-you-change-security-settings-and-user-rights-assignments-0cb6901b-dcbf-d1a9-e9ea-f1b49a56d53a

**Comment by frost-cqre** [comment]
Yes, but CIS benchmark for Windows (L1) in section 2.2.2 recommends restricting to "Administrators, Remote Desktop Users". I don't think it's a problem, but it might be useful to have it noted at least here as a reference.

I have created new local group %COMPUTERNAME%\MakeMeAdmin with GPO/Intune and assigned the right to this group. After that everything works correctly.

**Comment by pseymour** [comment]
My "issue," pardon the pun, is whether this constitutes an issue with Make Me Admin. It does not.

**Comment by frost-cqre** [comment]
Understood. I apologise for trying to make your software work in various environments. I will not do the mistake again.
