### ISSUE TITLE
Error on all GPO's after importing MakeMeAdmin template

### ISSUE THREAD

**Issue by Mohamed-abohussein** [pseymour/MakeMeAdmin#99]
Hi!

After i imported the ADMX/ADML into my on-premise Active Directory, it gives an error that some lines is not found

I tried several times to import the ADMX/ADML to the Central Store, but it gives me the same error on most of the GPO's

![MakeMeAdmin-Template-Error](https://github.com/pseymour/MakeMeAdmin/assets/7901730/09b95ec6-1baa-4711-a364-57c8adf09171)

**Comment by pseymour** [comment]
Which ADMX files are you importing? I have the current ones in the master branch imported into our AD, and there are no errors.

**Comment by Mohamed-abohussein** [comment]
Thank you for your reply.
I have imported both *.admx and *.adml in central store for 2 weeks ago but i have seen now that you have updated the templates *.admx and *.adml with new updates one week ago so i have downloaded them again and it seems working fine in my environment.
You can close this issue/request now and thank you again
